name: camillagui
channels:
dependencies:
  - pip
  - aiohttp
  - websocket-client
  - pip:
    - git+https://github.com/HEnquist/pycamilladsp.git@v1.0.0
    - git+https://github.com/HEnquist/pycamilladsp-plot.git@v1.0.2-rc1
    
