name: camillagui
channels:
dependencies:
  - pip
  - aiohttp
  - websocket-client
  - pip:
    - git+https://github.com/HEnquist/pycamilladsp.git@v0.5.0
    - git+https://github.com/HEnquist/pycamilladsp-plot.git@v0.5.3
    
