name: camillagui
channels:
dependencies:
  - pip
  - aiohttp
  - websocket-client
  - pip:
    - git+https://github.com/HEnquist/pycamilladsp.git@v2.0.0-alpha1
    - git+https://github.com/HEnquist/pycamilladsp-plot.git@v2.0.0-alpha1
    
