name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build_scripts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jinja2 PyYAML
    
    - name: Render scripts from templates
      run: python build_release.py

    - run: zip -r scripts.zip output/*
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: scripts.zip
        asset_name: scripts.zip
        tag: ${{ github.ref }}
